# Generated by Django 2.1.15 on 2020-11-19 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('department', models.CharField(max_length=16)),
                ('position', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Matter_Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('responsibility', models.CharField(max_length=16)),
                ('sme_nt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=16)),
                ('user_nt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Employee')),
            ],
        ),
    ]
