# Generated by Django 2.1.15 on 2020-11-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20201120_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject_matter_expert',
            name='responsibility',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.CharField(max_length=32),
        ),
    ]
