# Generated by Django 2.1.15 on 2020-11-20 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20201120_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_matter_expert',
            name='sme_nt_id',
        ),
        migrations.DeleteModel(
            name='Subject_Matter_Expert',
        ),
    ]
