# Generated by Django 2.1.15 on 2020-11-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20201120_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject_Matter_Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('responsibility', models.CharField(max_length=32)),
                ('sme_nt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Employee')),
            ],
        ),
    ]
