# Generated by Django 2.1.15 on 2020-11-23 23:44

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_subject_matter_expert'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nt_id',
            field=models.CharField(default=people.models.nt_id_default, max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_name',
            field=models.CharField(blank=True, choices=[('GrA', 'Group A'), ('GrB', 'Group B'), ('GrC', 'Group C'), ('GrD', 'Group D'), ('GrE', 'Group E')], max_length=16),
        ),
    ]
